# Generated by Django 4.0.5 on 2022-07-02 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Фамилия')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Url')),
                ('birth', models.DateField(blank=True, verbose_name='Дата рождения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('custumer_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('custumer_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('custumer_photo', models.ImageField(blank=True, upload_to='photos/catalog/%Y/%m/%d/', verbose_name='Фото')),
                ('custumer_position', models.CharField(blank=True, max_length=150, verbose_name='Должность')),
                ('custumer_adress', models.CharField(blank=True, max_length=150, verbose_name='Адрес')),
                ('custumer_comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('phisic_person', models.BooleanField(verbose_name='Физическое лицо')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Status_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус проекта',
                'verbose_name_plural': 'Статусы проектов',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Type_call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тип связи')),
            ],
            options={
                'verbose_name': 'Тип связи с Заказчиком',
                'verbose_name_plural': 'Типы связи с Заказчиком',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Url')),
                ('project_description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('project_photo', models.ImageField(blank=True, upload_to='photos/catalog/%Y/%m/%d/', verbose_name='Фото')),
                ('start_project', models.DateField(blank=True, verbose_name='Начало')),
                ('project_deadline', models.DateField(blank=True, verbose_name='Дедлайн')),
                ('in_charge', models.CharField(blank=True, max_length=150, verbose_name='Представитель Заказчика')),
                ('in_charge_phone', models.CharField(blank=True, max_length=150, verbose_name='Телефон представителя')),
                ('is_long', models.BooleanField(verbose_name='Длительный')),
                ('custumer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='crm.custumer', verbose_name='Заказчик')),
                ('status_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='crm.status_project', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='custumer',
            name='type_call',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='custumers', to='crm.type_call', verbose_name='Тип связи'),
        ),
    ]
