# Generated by Django 4.0.5 on 2022-07-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0002_alter_custumer_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_project',
            field=models.DateField(blank=True, null=True, verbose_name='Начало'),
        ),
    ]
