# Generated by Django 4.0.5 on 2022-07-02 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0003_alter_project_project_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custumer',
            name='type_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='custumers', to='crm.type_call', verbose_name='Тип связи'),
        ),
        migrations.AlterField(
            model_name='project',
            name='custumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='projects', to='crm.custumer', verbose_name='Заказчик'),
        ),
    ]
