# Generated by Django 4.0.5 on 2022-07-09 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0004_alter_custumer_type_call_alter_project_custumer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Akt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akt_title', models.CharField(blank=True, max_length=150, verbose_name='Название акта')),
                ('akt_number', models.CharField(blank=True, max_length=150, verbose_name='Номер акта')),
                ('akt_date', models.DateField(blank=True, null=True, verbose_name='Дата акта')),
                ('akt_file', models.FileField(blank=True, upload_to='docs/acts/', verbose_name='Файл акта')),
                ('akt_price', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Акт',
                'verbose_name_plural': 'Акты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Статус документа')),
            ],
            options={
                'verbose_name': 'Статус документа',
                'verbose_name_plural': 'Статусы документов',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='custumer',
            options={'ordering': ['id'], 'verbose_name': 'Заказчика', 'verbose_name_plural': 'Заказчики'},
        ),
        migrations.CreateModel(
            name='Schet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schet_title', models.CharField(blank=True, max_length=150, verbose_name='Название счета')),
                ('schet_number', models.CharField(blank=True, max_length=150, verbose_name='Номер счета')),
                ('schet_date', models.DateField(blank=True, null=True, verbose_name='Дата счета')),
                ('schet_file', models.FileField(blank=True, upload_to='docs/schets/', verbose_name='Файл счета')),
                ('schet_price', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Сумма')),
                ('document_status',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schets',
                                   to='crm.documentstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DogovorTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dogovor_task_title', models.CharField(blank=True, max_length=150, verbose_name='Название Задания')),
                ('task_number', models.CharField(blank=True, max_length=150, verbose_name='Номер Задания')),
                ('task_date', models.DateField(blank=True, null=True, verbose_name='Дата Задания')),
                ('task_file', models.FileField(blank=True, upload_to='docs/tasks/', verbose_name='Файл Задания')),
                ('task_price', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Сумма')),
                ('document_status',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dogovor_tasks',
                                   to='crm.documentstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Dogovor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dogovor_title', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('dogovor_number', models.CharField(blank=True, max_length=150, verbose_name='Номер Договора')),
                ('dogovor_date', models.DateField(blank=True, null=True, verbose_name='Дата Договора')),
                ('dogovor_file', models.FileField(blank=True, upload_to='docs/dogovors/', verbose_name='Файл')),
                ('dogovor_price',
                 models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Стоимость')),
                ('akt',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='crm.akt',
                                   verbose_name='Акт')),
                ('document_status',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects',
                                   to='crm.documentstatus', verbose_name='Статус')),
                ('dogovor_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects',
                                                   to='crm.dogovortask', verbose_name='Задание')),
                ('schet',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='crm.schet',
                                   verbose_name='Счет')),
            ],
            options={
                'verbose_name': 'Договора',
                'verbose_name_plural': 'Договоры',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='akt',
            name='document_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acts',
                                    to='crm.documentstatus', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='project',
            name='dogovor',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='dogovors', to='crm.dogovor', verbose_name='Договор'),
            preserve_default=False,
        ),
    ]
