# Generated by Django 4.0.5 on 2022-07-09 21:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0005_akt_documentstatus_alter_custumer_options_schet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akt',
            name='document_status',
        ),
        migrations.RemoveField(
            model_name='dogovortask',
            name='document_status',
        ),
        migrations.RemoveField(
            model_name='schet',
            name='document_status',
        ),
    ]
