# Generated by Django 4.0.5 on 2022-07-09 21:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0006_remove_akt_document_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogovor',
            name='akt',
        ),
        migrations.RemoveField(
            model_name='dogovor',
            name='document_status',
        ),
        migrations.RemoveField(
            model_name='dogovor',
            name='dogovor_task',
        ),
        migrations.RemoveField(
            model_name='dogovor',
            name='schet',
        ),
        migrations.DeleteModel(
            name='Akt',
        ),
        migrations.DeleteModel(
            name='DocumentStatus',
        ),
        migrations.DeleteModel(
            name='DogovorTask',
        ),
        migrations.DeleteModel(
            name='Schet',
        ),
    ]
