# Generated by Django 4.0.5 on 2022-07-09 21:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0008_alter_project_dogovor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='dogovor',
        ),
    ]
