# Generated by Django 4.0.5 on 2022-07-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0009_remove_project_dogovor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogovor',
            name='dogovor_file',
            field=models.FileField(blank=True, null=True, upload_to='docs/dogovors/', verbose_name='Файл'),
        ),
    ]
