# Generated by Django 4.0.5 on 2022-07-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0010_alter_dogovor_dogovor_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogovor',
            name='dogovor_title',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
