# Generated by Django 4.0.5 on 2022-07-09 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0011_alter_dogovor_dogovor_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dogovor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='dogovors', to='crm.dogovor', verbose_name='Договор'),
        ),
    ]
