# Generated by Django 4.0.5 on 2022-07-09 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0013_akt_documentstatus_dogovortask_schet_dogovor_akt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='akt',
            name='document_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='dogovor_akts', to='crm.documentstatus', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='dogovortask',
            name='document_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='dogovor_tasks', to='crm.documentstatus', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='schet',
            name='document_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='dogovor_schets', to='crm.documentstatus', verbose_name='Статус'),
        ),
    ]
