# Generated by Django 4.0.5 on 2022-07-09 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0016_remove_project_dogovor_project_dogovor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogovor',
            name='dogovor_task',
        ),
        migrations.AddField(
            model_name='dogovortask',
            name='dogovor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='projects', to='crm.dogovor', verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='dogovor',
            field=models.ManyToManyField(blank=True, related_name='dogovors', to='crm.dogovor', verbose_name='Договор'),
        ),
    ]
