# Generated by Django 4.0.5 on 2022-07-09 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0017_remove_dogovor_dogovor_task_dogovortask_dogovor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogovor',
            name='akt',
        ),
        migrations.RemoveField(
            model_name='dogovor',
            name='schet',
        ),
        migrations.AddField(
            model_name='akt',
            name='dogovor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='dogovor_acts', to='crm.dogovor', verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='schet',
            name='dogovor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='dogovor_schets', to='crm.dogovor', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='dogovortask',
            name='dogovor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='dogovor_tasks', to='crm.dogovor', verbose_name='Договор'),
        ),
    ]
