# Generated by Django 4.0.5 on 2022-07-09 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0018_remove_dogovor_akt_remove_dogovor_schet_akt_dogovor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogovor',
            name='custumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='dogovor_custumer', to='crm.custumer', verbose_name='Заказчик'),
        ),
    ]
