# Generated by Django 4.0.5 on 2022-07-10 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0019_dogovor_custumer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('short_name', models.CharField(blank=True, max_length=150, verbose_name='Короткое название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Url')),
                ('company_adress', models.TextField(blank=True, verbose_name='Адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлена')),
                ('company_phone_number', models.CharField(blank=True, max_length=150, verbose_name='Телефон')),
                ('company_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('inn', models.IntegerField(blank=True, verbose_name='ИНН')),
                ('kpp', models.IntegerField(blank=True, verbose_name='КПП')),
                ('ogrn', models.IntegerField(blank=True, verbose_name='ОГРН')),
                ('rs', models.IntegerField(blank=True, verbose_name='Расчетный счет')),
                ('bank_name', models.CharField(blank=True, max_length=150, verbose_name='Банк')),
                ('korr_schet', models.IntegerField(blank=True, verbose_name='Корреспондентский счет')),
                ('bik', models.IntegerField(blank=True, verbose_name='БИК')),
                ('director', models.CharField(max_length=150, verbose_name='Директор')),
                ('director_main', models.TextField(blank=True, verbose_name='На основании')),
                ('company_logo',
                 models.ImageField(blank=True, null=True, upload_to='companies_logo/', verbose_name='Логотип')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
        ),
        migrations.AlterField(
            model_name='custumer',
            name='custumer_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/catalog/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='custumer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='custumer_company', to='crm.company', verbose_name='Компания'),
        ),
    ]
