# Generated by Django 4.0.5 on 2022-07-10 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0020_company_alter_custumer_custumer_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тип парковки')),
            ],
            options={
                'verbose_name': 'Тип парковки',
                'verbose_name_plural': 'Типы парковок',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Статус задачи')),
            ],
            options={
                'verbose_name': 'Статус задачи',
                'verbose_name_plural': 'Статусы задач',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Url')),
                ('service_category_description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория услуги',
                'verbose_name_plural': 'Категории услуг',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Url')),
                ('service_description', models.TextField(blank=True, verbose_name='Описание')),
                ('service_price', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8,
                                                      verbose_name='Стоимость для клиента')),
                ('service_cost', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8,
                                                     verbose_name='Себестоимость')),
                ('service_category',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                   related_name='service_cat', to='crm.servicecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тип задачи')),
            ],
            options={
                'verbose_name': 'Тип задачи',
                'verbose_name_plural': 'Типы задач',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['id'], 'verbose_name': 'Компанию', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_task_title', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Url')),
                ('project_task_number', models.IntegerField(blank=True, verbose_name='Номер')),
                ('location', models.CharField(max_length=150, verbose_name='Локация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('task_start_date', models.DateField(blank=True, null=True, verbose_name='Начало')),
                ('task_deadline', models.DateField(blank=True, null=True, verbose_name='Дедлайн')),
                ('final_clip_Vimeo', models.URLField(blank=True, verbose_name='Финальное видео Vimeo')),
                ('final_clip_yandex', models.URLField(blank=True, verbose_name='Финальное видео ЯД')),
                ('parking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                              related_name='task_parking', to='crm.parking',
                                              verbose_name='Тип парковки')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                              related_name='project', to='crm.project', verbose_name='Проект')),
                ('project_task_status',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                   related_name='project_task_status', to='crm.projecttaskstatus',
                                   verbose_name='Статус задачи')),
                ('services', models.ManyToManyField(blank=True, related_name='tasks_services', to='crm.services',
                                                    verbose_name='Услуги')),
                ('task_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                                related_name='task_type', to='crm.tasktype',
                                                verbose_name='Тип задачи')),
            ],
            options={
                'verbose_name': 'Задачу',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at'],
            },
        ),
    ]
