# Generated by Django 4.0.5 on 2022-07-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0022_remove_task_project_task_number_alter_task_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['id'], 'verbose_name': 'Услугу', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='services',
            name='service_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Комментарий'),
        ),
    ]
