# Generated by Django 4.0.5 on 2022-07-11 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0023_alter_services_options_services_service_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfExecutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Должность')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='services',
            name='slug',
        ),
        migrations.AddField(
            model_name='services',
            name='type_of_executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='service_type_executor', to='crm.typeofexecutor',
                                    verbose_name='Сотрудник'),
        ),
    ]
