# Generated by Django 4.0.5 on 2022-07-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0024_typeofexecutor_remove_services_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='must_count',
            field=models.IntegerField(default=1, verbose_name='Кол-во'),
        ),
    ]
