# Generated by Django 4.0.5 on 2022-07-18 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0025_services_must_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название отдела')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FilePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_name', models.CharField(blank=True, max_length=100, verbose_name='Название директории')),
                ('path', models.CharField(blank=True, max_length=100, verbose_name='Путь')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('size', models.IntegerField(blank=True, default=0, verbose_name='Размер папки,МБ')),
                ('flash_card_count', models.IntegerField(blank=True, default=1, verbose_name='Количество флешек')),
            ],
            options={
                'verbose_name': 'Директория файла',
                'verbose_name_plural': 'Директории  файлов',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Url')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('phone_number', models.CharField(blank=True, max_length=100, verbose_name='Телефон')),
                ('executor_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('office', models.BooleanField(verbose_name='Офисный сотрудник')),
                ('executor_photo',
                 models.ImageField(blank=True, null=True, upload_to='executor_photo/', verbose_name='Фото')),
                ('passport_s', models.IntegerField(default=0, verbose_name='Серия паспорта')),
                ('passport_n', models.IntegerField(default=0, verbose_name='Номер паспорта')),
                ('birth_location', models.TextField(verbose_name='Место рождения')),
                ('adress_date', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('adress', models.TextField(verbose_name='Прописка')),
                ('vydan', models.TextField(verbose_name='Выдан')),
                ('data_vydachi', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('kod_podrazdelenia', models.IntegerField(default=0, verbose_name='Код подразделения')),
                ('driving_license', models.BooleanField(verbose_name='Наличие прав')),
                ('executor_cost', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8,
                                                      verbose_name='Себестоимость/час,₽')),
                ('department',
                 models.ManyToManyField(blank=True, related_name='executor_department', to='crm.department',
                                        verbose_name='Отдел')),
                ('file_path', models.ManyToManyField(blank=True, related_name='executor_filepath', to='crm.filepath',
                                                     verbose_name='Директория')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Марка')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='Регистрационный номер')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Цвет авто')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                               related_name='car_executor', to='crm.executor',
                                               verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Archives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archives_title', models.CharField(max_length=100, verbose_name='Название архива')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Url')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('full_size', models.IntegerField(blank=True, default=2000, verbose_name='Размер диска,МБ')),
                ('sn', models.CharField(blank=True, max_length=100, verbose_name='Серийный номер')),
                ('file_path', models.ManyToManyField(blank=True, related_name='archives_filepath', to='crm.filepath',
                                                     verbose_name='Директория')),
            ],
            options={
                'verbose_name': 'Архив',
                'verbose_name_plural': 'Архивы',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='archives',
            field=models.ManyToManyField(blank=True, related_name='tasks_archives', to='crm.archives',
                                         verbose_name='Архивы'),
        ),
        migrations.AddField(
            model_name='task',
            name='executor',
            field=models.ManyToManyField(blank=True, related_name='tasks_executor', to='crm.executor',
                                         verbose_name='Исполнители'),
        ),
    ]
