# Generated by Django 4.0.5 on 2022-07-18 01:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0026_department_filepath_executor_car_archives_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executor',
            options={'ordering': ['id'], 'verbose_name': 'Исполнителя', 'verbose_name_plural': 'Исполнители'},
        ),
        migrations.RemoveField(
            model_name='executor',
            name='file_path',
        ),
    ]
