# Generated by Django 4.0.5 on 2022-07-18 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0027_alter_executor_options_remove_executor_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Бренд оборудования',
                'verbose_name_plural': 'Бренды оборудования',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудования',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
                ('equipment_description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('sn', models.CharField(blank=True, max_length=100, verbose_name='s/n')),
                ('count', models.PositiveSmallIntegerField(blank=True, verbose_name='Кол-во')),
                ('owner_arenda', models.BooleanField(verbose_name='Аренда')),
                ('owner_office', models.BooleanField(verbose_name='Офисное оборудование')),
                ('equipment_cost', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8,
                                                       verbose_name='Себестоимость/час,₽')),
                ('equipment_price', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8,
                                                        verbose_name='Стоимость/час,₽')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка на аренду')),
                ('equipment_photo',
                 models.ImageField(blank=True, null=True, upload_to='equipment_photo/', verbose_name='Фото')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                            related_name='equipment_brand', to='crm.equipmentbrand',
                                            verbose_name='Бренд оборудования')),
                ('equipment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                                     related_name='equipment_type', to='crm.parking',
                                                     verbose_name='Тип оборудования')),
                ('owner_executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                                     related_name='equipment_executor', to='crm.executor',
                                                     verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['id'],
            },
        ),
    ]
