# Generated by Django 4.0.5 on 2022-07-18 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0030_equipment_buy_date_equipment_chek_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='equipment_type', to='crm.equipmenttype',
                                    verbose_name='Тип оборудования'),
        ),
    ]
