# Generated by Django 4.0.5 on 2022-07-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0031_alter_equipment_equipment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='roma',
            field=models.BooleanField(default=1, verbose_name='Украл Рома'),
            preserve_default=False,
        ),
    ]
