# Generated by Django 4.0.5 on 2022-07-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0032_equipment_roma'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8,
                                      verbose_name='Стоимость покупки'),
        ),
    ]
