# Generated by Django 4.0.5 on 2022-07-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0033_equipment_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archives',
            name='file_path',
        ),
        migrations.AddField(
            model_name='filepath',
            name='archives',
            field=models.ManyToManyField(blank=True, related_name='filepath_archives', to='crm.archives',
                                         verbose_name='Архив'),
        ),
    ]
