# Generated by Django 4.0.5 on 2022-07-18 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0034_remove_archives_file_path_filepath_archives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filepath',
            name='archives',
        ),
        migrations.AddField(
            model_name='filepath',
            name='archives',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='filepath_archives', to='crm.archives', verbose_name='Архив'),
        ),
    ]
