# Generated by Django 4.0.5 on 2022-07-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0035_remove_filepath_archives_filepath_archives'),
    ]

    operations = [
        migrations.AddField(
            model_name='executor',
            name='type_of_executor',
            field=models.ManyToManyField(blank=True, related_name='executor_type_of', to='crm.typeofexecutor',
                                         verbose_name='Должность'),
        ),
    ]
