# Generated by Django 4.0.5 on 2022-07-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0036_executor_type_of_executor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='executor',
        ),
        migrations.AddField(
            model_name='executor',
            name='car',
            field=models.ManyToManyField(blank=True, related_name='executor_car', to='crm.car', verbose_name='Авто'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='adress',
            field=models.TextField(blank=True, verbose_name='Прописка'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='birth_location',
            field=models.TextField(blank=True, verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='kod_podrazdelenia',
            field=models.IntegerField(blank=True, default=0, verbose_name='Код подразделения'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='passport_n',
            field=models.IntegerField(blank=True, default=0, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='passport_s',
            field=models.IntegerField(blank=True, default=0, verbose_name='Серия паспорта'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='vydan',
            field=models.TextField(blank=True, verbose_name='Выдан'),
        ),
    ]
