# Generated by Django 4.0.5 on 2022-07-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0038_remove_task_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filepath',
            options={'ordering': ['id'], 'verbose_name': 'Директорию файла',
                     'verbose_name_plural': 'Директории  файлов'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['id'], 'verbose_name': 'Категорию услуги', 'verbose_name_plural': 'Категории услуг'},
        ),
        migrations.AlterModelOptions(
            name='typeofexecutor',
            options={'ordering': ['id'], 'verbose_name': 'Сотрудника', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='company',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='company',
            name='bik',
            field=models.BigIntegerField(blank=True, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_phone_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='company',
            name='director',
            field=models.CharField(max_length=200, verbose_name='Директор'),
        ),
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.BigIntegerField(blank=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='company',
            name='korr_schet',
            field=models.BigIntegerField(blank=True, verbose_name='Корреспондентский счет'),
        ),
        migrations.AlterField(
            model_name='company',
            name='kpp',
            field=models.BigIntegerField(blank=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ogrn',
            field=models.BigIntegerField(blank=True, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='company',
            name='rs',
            field=models.BigIntegerField(blank=True, verbose_name='Расчетный счет'),
        ),
        migrations.AlterField(
            model_name='company',
            name='short_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Короткое название'),
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Url'),
        ),
    ]
