# Generated by Django 4.0.5 on 2022-07-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0039_alter_filepath_options_alter_servicecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='korr_schet',
            field=models.CharField(blank=True, max_length=30, verbose_name='Корреспондентский счет'),
        ),
        migrations.AlterField(
            model_name='company',
            name='rs',
            field=models.CharField(blank=True, max_length=30, verbose_name='Расчетный счет'),
        ),
    ]
