# Generated by Django 4.0.5 on 2022-07-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0040_alter_company_korr_schet_alter_company_rs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.TextField(blank=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='executor_cost',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, verbose_name='Ставка'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='kod_podrazdelenia',
            field=models.IntegerField(blank=True, verbose_name='Код подразделения'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='passport_n',
            field=models.IntegerField(blank=True, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='passport_s',
            field=models.IntegerField(blank=True, verbose_name='Серия паспорта'),
        ),
    ]
