# Generated by Django 4.0.5 on 2022-07-18 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0042_executorlevel_typeofinteraction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutorSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Навык Исполнителя',
                'verbose_name_plural': 'Навыки Исполнителей',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='akt',
            options={'ordering': ['id'], 'verbose_name': 'Акт', 'verbose_name_plural': '010_Акты'},
        ),
        migrations.AlterModelOptions(
            name='archives',
            options={'ordering': ['id'], 'verbose_name': 'Архив', 'verbose_name_plural': '011_Архивы'},
        ),
        migrations.AlterModelOptions(
            name='custumer',
            options={'ordering': ['id'], 'verbose_name': 'Заказчика', 'verbose_name_plural': '003_Заказчики'},
        ),
        migrations.AlterModelOptions(
            name='dogovor',
            options={'ordering': ['id'], 'verbose_name': 'Договор', 'verbose_name_plural': '007_Договоры'},
        ),
        migrations.AlterModelOptions(
            name='dogovortask',
            options={'ordering': ['id'], 'verbose_name': 'Задание', 'verbose_name_plural': '008_Задания'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['id'], 'verbose_name': 'Оборудование', 'verbose_name_plural': '006_Оборудование'},
        ),
        migrations.AlterModelOptions(
            name='executor',
            options={'ordering': ['id'], 'verbose_name': 'Исполнителя', 'verbose_name_plural': '004_Исполнители'},
        ),
        migrations.AlterModelOptions(
            name='filepath',
            options={'ordering': ['id'], 'verbose_name': 'Директорию файла', 'verbose_name_plural': '012_Директории  файлов'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Проект', 'verbose_name_plural': '001_Проекты'},
        ),
        migrations.AlterModelOptions(
            name='schet',
            options={'ordering': ['id'], 'verbose_name': 'Счет', 'verbose_name_plural': '009_Счета'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['id'], 'verbose_name': 'Услугу', 'verbose_name_plural': '005_Услуги'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Задачу', 'verbose_name_plural': '002_Задачи'},
        ),
        migrations.AddField(
            model_name='executor',
            name='executor_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.CreateModel(
            name='ExecutorPrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Программа')),
                ('executor_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programs_level', to='crm.executorlevel', verbose_name='Уровень владения')),
            ],
            options={
                'verbose_name': 'Работа в программах',
                'verbose_name_plural': 'Работа в программах',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='executor',
            name='executor_programs',
            field=models.ManyToManyField(blank=True, related_name='executor_programs', to='crm.executorprograms', verbose_name='Программы'),
        ),
        migrations.AddField(
            model_name='executor',
            name='executor_skills',
            field=models.ManyToManyField(blank=True, related_name='executor_skills', to='crm.executorskills', verbose_name='Навыки'),
        ),
    ]
