# Generated by Django 4.0.5 on 2022-07-18 19:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0043_executorskills_alter_akt_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executorprograms',
            name='executor_level',
        ),
    ]
