# Generated by Django 4.0.5 on 2022-07-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0045_alter_executor_kod_podrazdelenia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executor',
            name='credit_card',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Банковская карта'),
        ),
    ]
