# Generated by Django 4.0.5 on 2022-07-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0046_executor_credit_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('reference_url', models.URLField(blank=True, verbose_name='Ссылка на референс')),
                ('reference_comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('executor_skills',
                 models.ManyToManyField(blank=True, related_name='reference_skills', to='crm.executorskills',
                                        verbose_name='Навыки')),
            ],
            options={
                'verbose_name': 'Референс',
                'verbose_name_plural': 'Референсы',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='executor',
            name='reference',
            field=models.ManyToManyField(blank=True, related_name='executor_reference', to='crm.reference',
                                         verbose_name='Референс'),
        ),
    ]
