# Generated by Django 4.0.5 on 2022-07-19 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0047_reference_executor_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executor',
            options={'ordering': ['-id'], 'verbose_name': 'Исполнителя', 'verbose_name_plural': '004_Исполнители'},
        ),
        migrations.AddField(
            model_name='reference',
            name='executor_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='reference_level', to='crm.executorlevel', verbose_name='Уровень'),
        ),
    ]
