# Generated by Django 4.0.5 on 2022-07-19 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0048_alter_executor_options_reference_executor_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferencePlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Платформа для референсов',
                'verbose_name_plural': 'Платформы для референсов',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='reference',
            name='reference_platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='reference_platform', to='crm.referenceplatform',
                                    verbose_name='Платформа'),
        ),
    ]
