# Generated by Django 4.0.5 on 2022-07-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0049_referenceplatform_reference_reference_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='executor',
            field=models.ManyToManyField(blank=True, related_name='executor_reference', to='crm.executor',
                                         verbose_name='Исполнители'),
        ),
    ]
