# Generated by Django 4.0.5 on 2022-07-19 23:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0050_reference_executor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='executor',
        ),
    ]
