# Generated by Django 4.0.5 on 2022-07-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0051_remove_reference_executor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filepath',
            name='directory_name',
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Услуга'),
        ),
    ]
