# Generated by Django 4.0.5 on 2022-07-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0052_remove_filepath_directory_name_alter_services_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='archives',
        ),
        migrations.AddField(
            model_name='task',
            name='file_path',
            field=models.ManyToManyField(blank=True, related_name='tasks_file_path', to='crm.filepath',
                                         verbose_name='Расположение файлов'),
        ),
    ]
