# Generated by Django 4.0.5 on 2022-07-20 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0053_remove_task_archives_task_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Ед.измерения')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'единицы измерения',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='equipment',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='equipment_brand', to='crm.equipmentbrand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='owner_office',
            field=models.BooleanField(verbose_name='2You Studio'),
        ),
        migrations.AddField(
            model_name='executor',
            name='cost_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='executor_cost_value', to='crm.costvalue',
                                    verbose_name='ед.измерения'),
        ),
    ]
