# Generated by Django 4.0.5 on 2022-07-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0056_outcomingtarget_incoming_schet_outcoming'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=5, verbose_name='Приоритет выполнения'),
        ),
    ]
