# Generated by Django 4.0.5 on 2022-07-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0057_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='parking_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=40, max_digits=5, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=5, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project_task_title',
            field=models.CharField(max_length=150, verbose_name='Задача'),
        ),
    ]
