# Generated by Django 4.0.5 on 2022-07-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0058_parking_parking_price_alter_task_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custumer',
            name='custumer_tg',
            field=models.CharField(blank=True, max_length=100, verbose_name='Телеграм'),
        ),
    ]
