# Generated by Django 4.0.5 on 2022-07-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0059_custumer_custumer_tg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='count',
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='Кол-во'),
        ),
    ]
