# Generated by Django 4.0.5 on 2022-07-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0061_company_okpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='in_face',
            field=models.CharField(default=1, max_length=200, verbose_name='В лице'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='sign',
            field=models.CharField(default=1, max_length=200, verbose_name='Имя для подписи'),
            preserve_default=False,
        ),
    ]
