# Generated by Django 4.0.5 on 2022-07-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0062_company_in_face_company_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='company',
            name='bik',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='company',
            name='korr_schet',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Корреспондентский счет'),
        ),
        migrations.AlterField(
            model_name='company',
            name='kpp',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ogrn',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='company',
            name='okpo',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ОКПО'),
        ),
        migrations.AlterField(
            model_name='company',
            name='rs',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Расчетный счет'),
        ),
    ]
