# Generated by Django 4.0.5 on 2022-07-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0063_alter_company_bank_name_alter_company_bik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='director',
            field=models.CharField(blank=True, max_length=200, verbose_name='Директор'),
        ),
        migrations.AlterField(
            model_name='company',
            name='in_face',
            field=models.CharField(blank=True, max_length=200, verbose_name='В лице'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sign',
            field=models.CharField(blank=True, max_length=200, verbose_name='Имя для подписи'),
        ),
    ]
