# Generated by Django 4.0.5 on 2022-07-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0064_alter_company_director_alter_company_in_face_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='origin_tz',
            field=models.FileField(blank=True, null=True, upload_to='docs/tz/', verbose_name='Техническое задание'),
        ),
    ]
