# Generated by Django 4.0.5 on 2022-07-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0065_project_origin_tz'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='kp',
            field=models.FileField(blank=True, null=True, upload_to='docs/kp/', verbose_name='Коммерческое предложение'),
        ),
    ]
