# Generated by Django 4.0.5 on 2022-07-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0067_ispaid_project_project_cost_project_project_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custumer',
            options={'ordering': ['-id'], 'verbose_name': 'Заказчика', 'verbose_name_plural': '003_Заказчики'},
        ),
        migrations.AddField(
            model_name='task',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
    ]
