# Generated by Django 4.0.5 on 2022-08-01 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0068_alter_custumer_options_task_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Названия типа локации')),
            ],
            options={
                'verbose_name': 'Тип локации',
                'verbose_name_plural': 'Типы локации',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='task',
            name='location',
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Название локации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('location_adress', models.TextField(blank=True, verbose_name='Адрес локации')),
                ('location_cost', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True,
                                                      verbose_name='Себестоимость,₽/час')),
                ('location_url', models.URLField(blank=True, verbose_name='Ссылка на локацию')),
                ('location_phone', models.CharField(blank=True, max_length=100, verbose_name='Контактный телефон')),
                ('location_comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('location_photo_1',
                 models.ImageField(blank=True, null=True, upload_to='locations/', verbose_name='Фото 1')),
                ('location_photo_2',
                 models.ImageField(blank=True, null=True, upload_to='locations/', verbose_name='Фото 2')),
                ('location_photo_3',
                 models.ImageField(blank=True, null=True, upload_to='locations/', verbose_name='Фото 3')),
                ('location_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                                    related_name='location_type', to='crm.location_type',
                                                    verbose_name='Тип локации')),
                ('parking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                              related_name='location_parking', to='crm.parking',
                                              verbose_name='Тип парковки')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.ManyToManyField(blank=True, related_name='tasks_location', to='crm.location',
                                         verbose_name='Локация'),
        ),
    ]
