# Generated by Django 4.0.5 on 2022-08-01 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0069_location_type_remove_task_location_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['id'], 'verbose_name': 'Локацию', 'verbose_name_plural': '015_Локации'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='parking',
        ),
    ]
