# Generated by Django 4.0.5 on 2022-08-01 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0071_equipmentlocation_equipment_equipment_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Категория базы знаний',
                'verbose_name_plural': 'Категории базы знаний',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название статьи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('content', models.TextField(blank=True, verbose_name='Текст')),
                ('knowledge_base_photo',
                 models.ImageField(blank=True, upload_to='photos/knowledge_base/%Y/%m/%d/', verbose_name='Фото')),
                ('is_active', models.BooleanField(verbose_name='Опубликовано')),
                ('author',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_base_executor',
                                   to='crm.executor', verbose_name='Автор')),
                ('knowledge_base_category',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                   related_name='knowledge_base_category', to='crm.knowledgebasecategory',
                                   verbose_name='Категория базы знаний')),
            ],
            options={
                'verbose_name': 'Статью базы знаний',
                'verbose_name_plural': '016_Статьи базы знаний',
                'ordering': ['-created_at'],
            },
        ),
    ]
