# Generated by Django 4.0.5 on 2022-08-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0072_knowledgebasecategory_knowledgebaseitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgebaseitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Статью базы знаний', 'verbose_name_plural': '016_База знаний'},
        ),
        migrations.AddField(
            model_name='equipment',
            name='additional',
            field=models.TextField(blank=True, verbose_name='Дополнительное оборудование'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='defect',
            field=models.TextField(blank=True, verbose_name='Состояние/дефекты'),
        ),
    ]
