# Generated by Django 4.0.5 on 2022-08-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0073_alter_knowledgebaseitem_options_equipment_additional_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status_project',
            new_name='StatusProject',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='additional',
            field=models.TextField(blank=True, verbose_name='Комплектация'),
        ),
    ]
