# Generated by Django 4.0.5 on 2022-08-01 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0075_rename_type_call_typecall'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location_type',
            new_name='LocationType',
        ),
    ]
