# Generated by Django 4.0.5 on 2022-08-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0076_rename_location_type_locationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='archives',
            name='archives_photo',
            field=models.ImageField(blank=True, null=True, upload_to='archives_photo/', verbose_name='Фото'),
        ),
    ]
