# Generated by Django 4.0.5 on 2022-08-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0078_archives_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='archives',
            name='archives_subtitle',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название физического диска'),
        ),
        migrations.AlterField(
            model_name='archives',
            name='archives_title',
            field=models.CharField(max_length=100, verbose_name='Название на диске'),
        ),
        migrations.AlterField(
            model_name='archives',
            name='full_size',
            field=models.IntegerField(blank=True, default=1810, verbose_name='Размер диска,МБ'),
        ),
    ]
