# Generated by Django 4.0.5 on 2022-08-01 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0079_archives_archives_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Тип диска')),
            ],
            options={
                'verbose_name': 'Тип диска',
                'verbose_name_plural': 'Типы дисков',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='archives',
            name='type_of_archive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archives_type', to='crm.typeofarchive', verbose_name='Тип'),
        ),
    ]
