# Generated by Django 4.0.5 on 2022-08-01 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0080_typeofarchive_archives_type_of_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='План подписки')),
            ],
            options={
                'verbose_name': 'План подписки',
                'verbose_name_plural': 'Планы подписки',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Название программы/сервиса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('program_login', models.CharField(blank=True, max_length=150, verbose_name='Логин')),
                ('program_password', models.CharField(blank=True, max_length=150, verbose_name='Пароль')),
                ('program_license', models.TextField(blank=True, verbose_name='Лицензия')),
                ('activation_date', models.DateField(blank=True, null=True, verbose_name='Дата активации')),
                ('activation_for', models.DateField(blank=True, null=True, verbose_name='Дата окончания подписки')),
                ('program_cost', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, verbose_name='Стоимость,₽')),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_base_executor', to='crm.subscriptionplan', verbose_name='План подписки')),
            ],
            options={
                'verbose_name': 'Программу',
                'verbose_name_plural': '017_Программы и сервисы',
                'ordering': ['-created_at'],
            },
        ),
    ]
