# Generated by Django 4.0.5 on 2022-08-01 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0081_subscriptionplan_programitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Название компьютера')),
                ('subtitle', models.CharField(blank=True, max_length=150, verbose_name='Физическое название компьютера')),
                ('computer_password', models.CharField(blank=True, max_length=150, verbose_name='Пароль')),
                ('windows_license', models.TextField(blank=True, verbose_name='Лицензия Windows')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('cpu', models.CharField(blank=True, max_length=150, verbose_name='Процессор')),
                ('cpu_sn', models.CharField(blank=True, max_length=150, verbose_name='Процессор s/n')),
                ('motherboard', models.CharField(blank=True, max_length=150, verbose_name='Материнская плата')),
                ('motherboard_sn', models.CharField(blank=True, max_length=150, verbose_name='Материнская плата s/n')),
                ('ram_1', models.CharField(blank=True, max_length=150, verbose_name='Оперативная память 1')),
                ('ram_1_sn', models.CharField(blank=True, max_length=150, verbose_name='Оперативная память 1 s/n')),
                ('ram_2', models.CharField(blank=True, max_length=150, verbose_name='Оперативная память 2')),
                ('ram_2_sn', models.CharField(blank=True, max_length=150, verbose_name='Оперативная память 2 s/n')),
                ('ram_3', models.CharField(blank=True, max_length=150, verbose_name='Оперативная память 3')),
                ('ram_3_sn', models.CharField(blank=True, max_length=150, verbose_name='Оперативная память 3 s/n')),
                ('ram_4', models.CharField(blank=True, max_length=150, verbose_name='Оперативная память 4')),
                ('ram_4_sn', models.CharField(blank=True, max_length=150, verbose_name='Оперативная память 4 s/n')),
                ('videocard', models.CharField(blank=True, max_length=150, verbose_name='Видеокарта')),
                ('videocard_sn', models.CharField(blank=True, max_length=150, verbose_name='Видеокарта s/n')),
                ('power', models.CharField(blank=True, max_length=150, verbose_name='Блок питания')),
                ('power_sn', models.CharField(blank=True, max_length=150, verbose_name='Блок питания s/n')),
                ('wi_fi_module', models.BooleanField(verbose_name='Wi-fi модуль')),
                ('computer_photo', models.ImageField(blank=True, null=True, upload_to='computers/', verbose_name='Фото')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='computers_executor', to='crm.executor', verbose_name='Исполнитель')),
                ('hdd', models.ManyToManyField(blank=True, related_name='computers_archives', to='crm.archives', verbose_name='Жесткие диски')),
            ],
            options={
                'verbose_name': 'Компьютер',
                'verbose_name_plural': '018_Компьютеры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='programitem',
            name='computers',
            field=models.ManyToManyField(blank=True, related_name='program_computers', to='crm.computers', verbose_name='Компьютеры'),
        ),
    ]
