# Generated by Django 4.0.5 on 2022-08-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0082_computers_programitem_computers'),
    ]

    operations = [
        migrations.AddField(
            model_name='computers',
            name='keyboard',
            field=models.CharField(blank=True, max_length=150, verbose_name='Клавиатура'),
        ),
        migrations.AddField(
            model_name='computers',
            name='keyboard_sn',
            field=models.CharField(blank=True, max_length=150, verbose_name='Клавиатура s/n'),
        ),
        migrations.AddField(
            model_name='computers',
            name='monitor',
            field=models.CharField(blank=True, max_length=150, verbose_name='Монитор'),
        ),
        migrations.AddField(
            model_name='computers',
            name='monitor_sn',
            field=models.CharField(blank=True, max_length=150, verbose_name='Монитор s/n'),
        ),
        migrations.AddField(
            model_name='computers',
            name='mouse',
            field=models.CharField(blank=True, max_length=150, verbose_name='Мышь s/n'),
        ),
        migrations.AddField(
            model_name='computers',
            name='mouse_sn',
            field=models.CharField(blank=True, max_length=150, verbose_name='Мышь s/n'),
        ),
    ]
