# Generated by Django 4.0.5 on 2022-08-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0084_computers_corpus'),
    ]

    operations = [
        migrations.AddField(
            model_name='programitem',
            name='program_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Почта для аккаунта'),
        ),
        migrations.AddField(
            model_name='programitem',
            name='program_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на сервис'),
        ),
    ]
