# Generated by Django 4.0.5 on 2022-08-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0085_programitem_program_email_programitem_program_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='programitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
            preserve_default=False,
        ),
    ]
